name: Lint & Build
run-name: ${{ github.actor }} is ensuring code quality. :)
on: [push]
jobs:
  Test-OMP:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install clang-format
      - name: Link
        run: run: echo "FORMAT_ISSUES=$(cd src && clang-format --dry-run *.cc *.h)" >> $GITHUB_ENV
