name: Lint & Build
run-name: ${{ github.actor }} is ensuring code quality. :)
on: [push]
jobs:
  Test-OMP:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install meson libgtk-4-dev libadwaita-1-dev
      - name: Prepare Build
        run: meson setup builddir
      - name: Run Build
        run: meson compile -v -C builddir
