name: Lint & Build
run-name: ${{ github.actor }} is ensuring code quality. :)
on: [push]
jobs:
  Test-OMP:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install clang-format
      - name: Link
        id: format_check
        run: |
          cd src
          errors=$(clang-format --dry-run *.cc *.h 2>&1; echo $?)
          if [ -z "$errors" ]
          then
              echo "Format is valid. Nice!"
          else
              echo "::error::Formatting errors exist."
              exit 1
          fi
